stages:
  - build-and-test
  - benchmark
  - benchmark-completion

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_VERSION_CHECK: ignore
  GRAALEE_VERSION: oracle-graalvm-ea-jdk-25i2-25.0.3-ea.04
  JAVA_VERSION: temurin-25.0.2+10.0.LTS

.shared-scripts:
  download-binaries: &DOWNLOAD_BINARIES |
    download_and_decompress som-native-interp-ast
    download_and_decompress som-native-interp-bc
    download_and_decompress som-native-interp-op
    download_and_decompress som-native-interp-ast-ee || true
    download_and_decompress som-native-interp-bc-ee  || true
    download_and_decompress som-native-interp-op-ee  || true

before_script:
  - source .github/ci.sh
  - ensure_core_lib_and_its_remotes
  - ./som --setup latest-mx
  - ensure_mx_on_path
  - reown_graal
  - reset_graal_to_imported_version
  - install_dependencies
    

test:
  stage: build-and-test
  tags: [kent-yuria4]
  script:
    - ensure_labsjdk_and_graal_version

    - mx build
    - mx tests-junit
    - mx tests-som
    - mx tests-somsom
    - mx build-native-image-tool
    - mx build-native-obj-test
    - ./som-obj-storage-tester

    - export JAVA_HOME=`pwd`/libs/jvmci
    - (cd ../graal/tools && mx build)
    - mx tests-nodestats || true
    - mx tests-coverage || true

build:native-interp-ast:
  stage: build-and-test
  tags: [kent-yuria2]
  allow_failure:
    exit_codes: 70 # EE failed building
  script:
    - ensure_labsjdk_and_graal_version

    - mx build
    - mx build-native --no-jit -t AST -bn
    - ./som-native-interp-ast -cp Smalltalk TestSuite/TestHarness.som
    - compress_and_upload som-native-interp-ast

    - |
      EE_FAILED=0
      if mx build-native --no-jit -t AST -g ${GRAALEE_HOME}; then
        ./som-native-interp-ast-ee -cp Smalltalk TestSuite/TestHarness.som
        compress_and_upload som-native-interp-ast-ee
      else
        EE_FAILED=70
      fi
      exit $EE_FAILED

build:native-interp-bc:
  stage: build-and-test
  tags: [kent-yuria3]
  allow_failure:
    exit_codes: 70 # EE failed building
  script:
    - ensure_labsjdk_and_graal_version

    - mx build
    - mx build-native --no-jit -t BC -bn
    - ./som-native-interp-bc -cp Smalltalk TestSuite/TestHarness.som
    - compress_and_upload som-native-interp-bc

    - |
      EE_FAILED=0
      if mx build-native --no-jit -t BC -g ${GRAALEE_HOME}; then
        ./som-native-interp-bc-ee -cp Smalltalk TestSuite/TestHarness.som
        compress_and_upload som-native-interp-bc-ee
      else
        EE_FAILED=70
      fi
      exit $EE_FAILED

build:native-interp-op:
  stage: build-and-test
  tags: [yuria]
  script:
    - *ENSURE_LABSJDK_AND_GRAAL_VERSION

    - mx build
    - mx build-native -J -t OP -bn
    - ./som-native-interp-op -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native -J -t OP -g ${GRAALEE_HOME}
    - ./som-native-interp-op-ee -cp Smalltalk TestSuite/TestHarness.som

    - lz4 som-native-interp-op som-native-interp-op.lz4
    - lz4 som-native-interp-op-ee som-native-interp-op-ee.lz4
    - |
      sftp tmp-artifacts << EOF
        -mkdir incoming/${CI_PIPELINE_ID}/
        put som-native-interp-op.lz4 incoming/${CI_PIPELINE_ID}/
        put som-native-interp-op-ee.lz4 incoming/${CI_PIPELINE_ID}/
      EOF

build:aarch64-test-and-rebench:
  stage: build-and-test
  tags: [kent-zullie1]
  script:
    - pmset -g live
    - pmset -g systemstate

    - ensure_labsjdk_and_graal_version

    - mx build
    - mx --env libgraal build
    - mx tests-junit
    - mx tests-som
    - mx tests-somsom
    - mx build-native-image-tool

    - mx build-native-obj-test
    - ./som-obj-storage-tester

    - mx build-native --no-jit -t BC
    - ./som-native-interp-bc -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t AST
    - ./som-native-interp-ast -cp Smalltalk TestSuite/TestHarness.som

    - |
      EE_FAILED=0
      if mx build-native --no-jit -t BC -g ${GRAALEE_HOME}; then
        ./som-native-interp-bc-ee -cp Smalltalk TestSuite/TestHarness.som
      else
        EE_FAILED=70
      fi

    - |
      if mx build-native --no-jit -t AST -g ${GRAALEE_HOME}; then
        ./som-native-interp-ast-ee -cp Smalltalk TestSuite/TestHarness.som
      else
        EE_FAILED=70
      fi

    - mx tests-nodestats || true
    - mx tests-coverage || true

    - export PATH=$PATH:/Users/gitlab-runner/Library/Python/3.12/bin
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf
    - exit $EE_FAILED

benchmark-y1:
  stage: benchmark
  needs:
    [
      "build:native-interp-ast",
      "build:native-interp-bc",
      "build:native-interp-op",
    ]

  tags: [kent-yuria]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria
  after_script:
    - sudo reown-project.sh

benchmark-y2:
  stage: benchmark
  needs:
    [
      "build:native-interp-ast",
      "build:native-interp-bc",
      "build:native-interp-op",
    ]
  tags: [kent-yuria2]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria2
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria2
  after_script:
    - sudo reown-project.sh

benchmark-y3:
  stage: benchmark
  needs:
    [
      "build:native-interp-ast",
      "build:native-interp-bc",
      "build:native-interp-op",
    ]
  tags: [kent-yuria3]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria3
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria3
  after_script:
    - sudo reown-project.sh

benchmark-y4:
  stage: benchmark
  needs:
    [
      "build:native-interp-ast",
      "build:native-interp-bc",
      "build:native-interp-op",
    ]
  tags: [kent-yuria4]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria4
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria4
  after_script:
    - sudo reown-project.sh

report-completion:
  stage: benchmark-completion
  tags: [kent-yuria]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
