stages:
  - build-and-test
  - benchmark
  - benchmark-completion

variables:
  PYTHONUNBUFFERED: "true"
  JVMCI_VERSION_CHECK: ignore
  GRAALEE_VERSION: oracle-graalvm-ea-jdk-25i2-25.0.3-ea.04
  JAVA_VERSION: temurin-25.0.2+10.0.LTS

.shared-scripts:
  download-binaries: &DOWNLOAD_BINARIES |
    download_and_decompress som-native-interp-ast
    download_and_decompress som-native-interp-bc
    download_and_decompress som-native-interp-ast-ee
    download_and_decompress som-native-interp-bc-ee

before_script:
  - source .github/ci.sh
  - ensure_core_lib_and_its_remotes
  - ./som --setup latest-mx
  - ensure_mx_on_path
  - reown_graal
  - reset_graal_to_imported_version
  - install_dependencies
    

test:
  stage: build-and-test
  tags: [kent-yuria4]
  script:
    - ensure_labsjdk_and_graal_version

    - mx build
    - mx tests-junit
    - mx tests-som
    - mx tests-somsom
    - mx build-native-image-tool
    - mx build-native-obj-test
    - ./som-obj-storage-tester

    - export JAVA_HOME=`pwd`/libs/jvmci
    - (cd ../graal/tools && mx build)
    - mx tests-nodestats || true
    - mx tests-coverage || true

build:native-interp-ast:
  stage: build-and-test
  tags: [kent-yuria2]
  script:
    - ensure_labsjdk_and_graal_version

    - mx build
    - mx build-native --no-jit -t AST -bn
    - ./som-native-interp-ast -cp Smalltalk TestSuite/TestHarness.som
    - compress_and_upload som-native-interp-ast

    - mx build-native --no-jit -t AST -g ${GRAALEE_HOME}
    - ./som-native-interp-ast-ee -cp Smalltalk TestSuite/TestHarness.som
    - compress_and_upload som-native-interp-ast-ee

build:native-interp-bc:
  stage: build-and-test
  tags: [kent-yuria3]
  script:
    - ensure_labsjdk_and_graal_version

    - mx build
    - mx build-native --no-jit -t BC -bn
    - ./som-native-interp-bc -cp Smalltalk TestSuite/TestHarness.som
    - compress_and_upload som-native-interp-bc

    - mx build-native --no-jit -t BC -g ${GRAALEE_HOME}
    - ./som-native-interp-bc-ee -cp Smalltalk TestSuite/TestHarness.som
    - compress_and_upload som-native-interp-bc-ee

build:aarch64-test-and-rebench:
  stage: build-and-test
  tags: [kent-zullie1]
  script:
    - pmset -g live
    - pmset -g systemstate

    - ensure_labsjdk_and_graal_version

    - mx build
    - mx --env libgraal build
    - mx tests-junit
    - mx tests-som
    - mx tests-somsom
    - mx build-native-image-tool

    - mx build-native-obj-test
    - ./som-obj-storage-tester

    - mx build-native --no-jit -t BC
    - ./som-native-interp-bc -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t AST
    - ./som-native-interp-ast -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t BC -g ${GRAALEE_HOME}
    - ./som-native-interp-bc-ee -cp Smalltalk TestSuite/TestHarness.som

    - mx build-native --no-jit -t AST -g ${GRAALEE_HOME}
    - ./som-native-interp-ast-ee -cp Smalltalk TestSuite/TestHarness.som

    - mx tests-nodestats || true
    - mx tests-coverage || true

    - export PATH=$PATH:/Users/gitlab-runner/Library/Python/3.12/bin
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf

benchmark-y1:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [kent-yuria]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria
  after_script:
    - sudo reown-project.sh

benchmark-y2:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [kent-yuria2]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria2
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria2
  after_script:
    - sudo reown-project.sh

benchmark-y3:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [kent-yuria3]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria3
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria3
  after_script:
    - sudo reown-project.sh

benchmark-y4:
  stage: benchmark
  needs: ["build:native-interp-ast", "build:native-interp-bc"]
  tags: [kent-yuria4]
  script:
    - build_with_libgraal
    - *DOWNLOAD_BINARIES

    # Profile
    - rebench -f -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf profiling t:yuria4
    # Run Benchmarks
    - rebench -c --experiment="CI ID $CI_PIPELINE_ID" --branch="$CI_COMMIT_REF_NAME" rebench.conf t:yuria4
  after_script:
    - sudo reown-project.sh

report-completion:
  stage: benchmark-completion
  tags: [kent-yuria]
  script:
    - rebench --experiment="CI ID $CI_PIPELINE_ID" --report-completion rebench.conf
